"""C2PA / Content Credentials signing for published videos.

Embeds a cryptographically-signed provenance manifest declaring the video as
AI-generated by Stephen Spielbot. Best-effort: when c2patool is not installed
(or signing fails) we log and skip, exactly like the rest of the media pipeline.

Signing must be the LAST thing to touch the bytes — C2PA hash-binds the file, so
any later re-encode invalidates the manifest. We therefore sign in place right
before a video is published (see the upload / X-post tasks).

Certificate model: honor a configured cert/key (``c2pa_cert_path`` /
``c2pa_key_path``); otherwise auto-generate a local self-signed ES256 cert under
the app config dir (never committed). A self-signed cert embeds valid, readable
Content Credentials, but validators show "issued by an unknown source" until a
trust-listed certificate is configured.
"""
from __future__ import annotations

import json
import logging
import os
import shutil
import subprocess
import tempfile
from pathlib import Path

from pipeline.assembler import _resolve_media_tool

logger = logging.getLogger("video_gen")

REPO_URL = "https://github.com/pizzato/stephen_spielbot"
# IPTC DigitalSourceType for media wholly created by a generative AI model.
_AI_SOURCE_TYPE = "http://cv.iptc.org/newscodes/digitalsourcetype/trainedAlgorithmicMedia"

_C2PATOOL = _resolve_media_tool("c2patool")
_OPENSSL = _resolve_media_tool("openssl")

# Self-signed cert/key live beside the single YAML config, never in the repo.
_C2PA_DIR = Path.home() / ".config" / "video-generator" / "c2pa"
_AUTO_CERT = _C2PA_DIR / "cert.pem"
_AUTO_KEY = _C2PA_DIR / "key.pem"


def _have(tool: str) -> bool:
    """Whether a resolved tool path is actually runnable."""
    return bool(shutil.which(tool) or (os.path.isabs(tool) and Path(tool).exists()))


def _manifest_json() -> str:
    """A minimal, valid C2PA manifest: credits Stephen Spielbot and declares the
    asset AI-generated (the meaningful provenance signal)."""
    return json.dumps({
        "alg": "es256",
        "claim_generator_info": [{"name": "Stephen Spielbot"}],
        "assertions": [
            {
                "label": "c2pa.actions",
                "data": {"actions": [{
                    "action": "c2pa.created",
                    "softwareAgent": f"Stephen Spielbot ({REPO_URL})",
                    "digitalSourceType": _AI_SOURCE_TYPE,
                }]},
            },
        ],
    })


def _ensure_cert(cert_path: Path, key_path: Path) -> bool:
    """Generate a self-signed ES256 signing cert/key if missing. Returns True
    when a usable pair exists. Best-effort — needs openssl."""
    if cert_path.exists() and key_path.exists():
        return True
    if not _have(_OPENSSL):
        logger.warning("[c2pa] openssl not found — cannot auto-generate a signing cert")
        return False
    cert_path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with tempfile.TemporaryDirectory() as td:
            ec_key = Path(td) / "ec.key"
            # ES256 = ECDSA over P-256.
            subprocess.run([_OPENSSL, "ecparam", "-name", "prime256v1", "-genkey",
                            "-noout", "-out", str(ec_key)], check=True, capture_output=True)
            # The C2PA cert profile wants a non-CA leaf with digitalSignature key
            # usage and an allowed EKU (emailProtection is one).
            subprocess.run([
                _OPENSSL, "req", "-new", "-x509", "-key", str(ec_key),
                "-out", str(cert_path), "-days", "3650",
                "-subj", "/CN=Stephen Spielbot/O=Stephen Spielbot",
                "-addext", "basicConstraints=critical,CA:FALSE",
                "-addext", "keyUsage=critical,digitalSignature",
                "-addext", "extendedKeyUsage=emailProtection",
            ], check=True, capture_output=True)
            # c2patool signs ES256 from a PKCS#8 private key.
            subprocess.run([_OPENSSL, "pkcs8", "-topk8", "-nocrypt",
                            "-in", str(ec_key), "-out", str(key_path)],
                           check=True, capture_output=True)
    except Exception as e:
        logger.warning("[c2pa] self-signed cert generation failed: %s", e)
        return False
    try:
        key_path.chmod(0o600)
    except Exception:
        pass
    logger.info("[c2pa] generated self-signed signing cert at %s", cert_path)
    return cert_path.exists() and key_path.exists()


def _sign(path: Path, cert_path: Path, key_path: Path) -> bool:
    """Embed the manifest into *path* in place (atomic swap). Returns success."""
    env = dict(os.environ)
    env["C2PA_PRIVATE_KEY"] = key_path.read_text()
    env["C2PA_SIGN_CERT"] = cert_path.read_text()
    # Write the signed copy next to the target (same volume) then atomically
    # swap, so a mid-write failure never corrupts the published video.
    tmp_out = path.with_name(f"{path.stem}.c2pa.tmp{path.suffix}")
    try:
        with tempfile.TemporaryDirectory() as td:
            mpath = Path(td) / "manifest.json"
            mpath.write_text(_manifest_json())
            r = subprocess.run(
                [_C2PATOOL, str(path), "-m", str(mpath), "-o", str(tmp_out), "-f"],
                env=env, capture_output=True, text=True, timeout=300,
            )
        if r.returncode != 0:
            logger.warning("[c2pa] c2patool failed: %s", (r.stderr or r.stdout).strip()[:300])
            return False
        if not tmp_out.exists() or tmp_out.stat().st_size < 1000:
            logger.warning("[c2pa] c2patool produced no usable output")
            return False
        tmp_out.replace(path)
        return True
    finally:
        try:
            tmp_out.unlink(missing_ok=True)
        except Exception:
            pass


def sign_if_enabled(path, cfg: dict) -> bool:
    """Best-effort: sign *path* in place with Content Credentials when C2PA is
    enabled in *cfg*. Never raises — a signing failure must not block a publish.
    """
    try:
        if not cfg.get("c2pa_enabled", True):
            return False
        if not _have(_C2PATOOL):
            logger.info("[c2pa] c2patool not installed — skipping Content Credentials "
                        "(install: brew install c2patool)")
            return False
        p = Path(path)
        if not p.exists():
            return False
        cert = str(cfg.get("c2pa_cert_path") or "").strip()
        key = str(cfg.get("c2pa_key_path") or "").strip()
        if cert and key:
            cert_path, key_path = Path(cert).expanduser(), Path(key).expanduser()
            if not (cert_path.exists() and key_path.exists()):
                logger.warning("[c2pa] configured cert/key not found — skipping")
                return False
        else:
            cert_path, key_path = _AUTO_CERT, _AUTO_KEY
            if not _ensure_cert(cert_path, key_path):
                return False
        if _sign(p, cert_path, key_path):
            logger.info("[c2pa] signed Content Credentials into %s", p.name)
            return True
        return False
    except Exception as e:
        logger.warning("[c2pa] signing skipped: %s", e)
        return False
